# Generated by Django 4.1.4 on 2022-12-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('dp', models.ImageField(default='', upload_to='')),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
                ('Department', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('ZipCode', models.IntegerField()),
                ('State', models.CharField(max_length=100)),
                ('Active', models.BooleanField()),
                ('on_leave', models.BooleanField()),
            ],
        ),
    ]
