# Generated by Django 4.1.4 on 2022-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dp',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
