# Generated by Django 4.1.4 on 2022-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_leave_count_alter_employee_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='on_leave',
            field=models.BooleanField(default='False'),
        ),
    ]
