# Generated by Django 4.1.4 on 2022-12-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_dob_alter_employee_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOJ',
            field=models.DateField(),
        ),
    ]
