# Generated by Django 4.1.4 on 2022-12-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_dob_alter_employee_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dp',
            field=models.FileField(default='default.png', upload_to=''),
        ),
    ]
